name: filter-branches-tags-paths
on:
  pull_request:
    branches:
      - filtered_branch
    tags:
      - filtered_tag
    paths:
      - filtered_path

jobs:
  echo_hello:
   name: Echo
   runs-on: ubuntu-latest
   steps:
     - name: echo filterring
       run: echo 'Filtering branches/tags and paths!'
  
